In [137]:
import numpy as np
from numpy.linalg import norm

# Input

In [138]:
# Power function
def f(x):
    global counter
    counter += 1
    return((x[0]-1)**2 + (x[1]-1)**2)

# Rosenbrock function
# def f(x):
#     return((1-x[0])**2 + 100*(x[1]-x[0]**2)**2)

x0 = np.array([-1.2, 0])

h = 10**-2
# h = 10**-3
# h = 10**-5

eps = 10**-5

# Derivatives

In [145]:
def der_f_left(x, h, i):
    hi = np.array([0.0, 0.0])
    hi[i] = h
    return((f(x) - f(x-hi))/h)

def der_f_center(x, h, i):
    hi = np.array([0.0, 0.0])
    hi[i] = h
    return((f(x+hi) - f(x-hi))/(2*h))

def der_f_right(x, h, i):
    hi = np.array([0.0, 0.0])
    hi[i] = h
    return((f(x+hi) - f(x))/h)

def der_f(x, h, i):
    return(der_f_center(x, h, i))

def grad_f(x, h=h):
    return(np.array([
        der_f(x, h, i=0),
        der_f(x, h, i=1)
    ]))

In [146]:
def antigrad_direction(x):
    return(-grad_f(x, h) / norm(grad_f(x, h)))
antigrad_direction(x0)

array([0.91036648, 0.41380294])

# Swann

In [148]:
def swann(x, delta, direct):
    xs = [x]
    i = 0
    
    x_positive = xs[-1] + direct * delta * 2**i
    x_negative = xs[-1] - direct * delta * 2**i
#     if f(x) < f(x_negative) and f(x) < f(x_positive):
#         return([x, x])
    if f(x_negative) < f(x_positive):
        direct = -direct

    while True:
        x = xs[-1] + direct * delta * 2**i
        if f(xs[-1]) < f(x):
            x_half = xs[-1] + direct * delta * 2**(i-1)
            xs.append(x_half)
            xs.append(x)
            break;
        else:
            xs.append(x)
            i += 1

    if len(xs) > 3 and f(xs[-3]) < f(xs[-2]):
        interval = [xs[-4], xs[-2]]
    else:
        interval = [xs[-3], xs[-1]]
    return(interval)

interval = swann(x0, delta=h, direct=antigrad_direction(x0))
interval

[array([-0.04383457,  0.52552974]), array([2.28670361, 1.58486528])]

# Golden ratio

In [149]:
def golden_ratio(interval, direct):
    x_positive = interval[0] + direct
    x_negative = interval[1] - direct
    if f(x_negative) <= f(x_positive):
        direct = -direct

    step = 0.618
    a = interval[0]
    b = interval[1]
    l = b - a
    x1 = a + (1 - step) * norm(l) * direct
    x2 = a + step * norm(l) * direct

    while True:
        if f(x1) <= f(x2):
            a = a
            b = x2
            l = b - a
            x2 = x1
            x1 = a + (1 - step) * norm(l) * direct
        else:
            a = x1
            b = b
            l = b - a
            x1 = x2
            x2 = a + step * norm(l) * direct
        if norm(l) < eps:
            x = x1 if f(x1) < f(x2) else x2
            return(x)

x = golden_ratio(interval, direct=antigrad_direction(x0))
x

array([0.99999903, 0.99999956])

# DSK-Powell method

In [159]:
def dsk_powell(interval, direct):
    # DSK
    x1, x3 = interval
    x2 = (x1 + x3)/2
    delta_x = norm(x1-x2)
    x_star = x2 + delta_x * (f(x1) - f(x3)) / (2 * (f(x1) - 2*f(x2) + f(x3)))
    m = min([x1, x2, x3], key=lambda x: f(x))

    exit_criteria = norm(f(x1) - f(m)) < eps and norm(x1 - m) < eps

    xs = sorted([x1, x2, x3, x_star], key=lambda x: x[0])
    m = min(xs, key=lambda x: f(x))

    if f(xs[1]) == f(m):
        x1 = xs[0]
        x2 = xs[1]
        x3 = xs[2]
    else:
        x1 = xs[1]
        x2 = xs[2]
        x3 = xs[3]

        
    # Powell    
    while not exit_criteria:
        a1 = (f(x2) - f(x1)) / (x2 - x1)
        a2 = ((f(x3) - f(x1) / (x3 - x1)) - ((f(x2) - f(x1)) / (x2 - x1))) / (x3 - x2)
        x_star = ((x2 + x1) / 2) - a1 / (2 * a2)

        m = min([x1, x2, x3], key=lambda x: f(x))
        
        exit_criteria = norm(f(x1) - f(m)) < eps and norm(x1 - m) < eps

        xs = sorted([x1, x2, x3, x_star], key=lambda x: x[0])
        m = min(xs, key=lambda x: f(x))
        
        if f(xs[1]) == f(m):
            if f(x1) == f(xs[0]) and f(x2) == f(xs[1]) and f(x3) == f(xs[2]):
                return(m)
            x1 = xs[0]
            x2 = xs[1]
            x3 = xs[2]
        else:
            if f(x1) == f(xs[1]) and f(x2) == f(xs[2]) and f(x3) == f(xs[3]):
                return(m)
            x1 = xs[1]
            x2 = xs[2]
            x3 = xs[3]
    return(m)

x = dsk_powell(interval, direct=antigrad_direction(x0))
x

array([1.01134003, 0.99448106])

In [169]:
def find_min_in_direction(x0, direction):
    interval = swann(x0, delta=h, direct=direction)
#     x = dsk_powell(interval, direct=direction)
    x = golden_ratio(interval, direct=direction)
    return(x)

# Partan method

In [170]:
xs = [x0]
directions = []
grad_exit_criteria = False
eps = 10**-3
counter = 0

while(not grad_exit_criteria):
    # antigrad direction
    direction = antigrad_direction(xs[-1])
    directions.append(direction)
    x = find_min_in_direction(xs[-1], directions[-1])
    xs.append(x)

    # antigrad direction
    direction = antigrad_direction(xs[-1])
    x = find_min_in_direction(xs[-1], direction)
    xs.append(x)

    # partan direction
    direction = xs[-1] - xs[-3]
    x = find_min_in_direction(xs[-1], direction)
    xs.append(x)

    grad_exit_criteria = norm(grad_f(xs[-1])) < eps
print(counter)
for i, x in enumerate(xs):
    print(f"f(x{i}) = f({x}) = {f(x)}")

200
f(x0) = f([-1.2  0. ]) = 5.840000000000001
f(x1) = f([1.00004843 1.00002201]) = 2.8302040222158755e-09
f(x2) = f([1.00036204 1.00016457]) = 1.581582938200643e-07
f(x3) = f([1.02067791 1.00939905]) = 0.0005159182703755073
f(x4) = f([1.01187045 1.00539566]) = 0.0001700208360876086
f(x5) = f([0.9999911  0.99999595]) = 9.563414268731015e-11
f(x6) = f([0.99999107 0.99999594]) = 9.617668692002813e-11


# Modified Partan method

In [136]:
xs = [x0]
# First step of a regular Partan method
# antigrad_direction
direction = antigrad_direction(xs[-1])
x = find_min_in_direction(xs[-1], direction)
xs.append(x)
# antigrad_direction
direction = antigrad_direction(xs[-1])
x = find_min_in_direction(xs[-1], direction)
xs.append(x)
# partan direction
direction = xs[-3] - xs[-1]
x = find_min_in_direction(xs[-1], direction)
xs.append(x)

grad_exit_criteria = False

while(not grad_exit_criteria):
    # antigrad_direction
    direction = antigrad_direction(xs[-1])
    x = find_min_in_direction(xs[-1], direction)
    xs.append(x)

    # modified partan direction
    direction = xs[-1] - xs[-4]
    x = find_min_in_direction(xs[-1], direction)
    xs.append(x)

    grad_exit_criteria = norm(grad_f(xs[-1])) < eps

for i, x in enumerate(xs):
    print(f"f(x{i}) = f({x}) = {f(x)}")

f(x0) = f([-1.2  0. ]) = 5.840000000000001
f(x1) = f([0.99999903 0.99999956]) = 1.1347466399070316e-12
f(x2) = f([0.99999648 0.9999984 ]) = 1.4956942676831313e-11
f(x3) = f([0.97968736 0.99076698]) = 0.0004978519410157535
f(x4) = f([0.98878862 0.99490392]) = 0.0001516652015117905
f(x5) = f([0.99585117 0.99811417]) = 2.0769106690942587e-05
f(x6) = f([0.99584862 0.99811301]) = 2.0794655330569955e-05
f(x7) = f([0.99827281 0.99921491]) = 3.5995444161504934e-06
f(x8) = f([0.99827026 0.99921375]) = 3.610185105002426e-06
f(x9) = f([0.99999993 0.99999997]) = 5.486478914467565e-15
