In [2]:
import numpy as np
from numpy.linalg import inv

In [3]:
def f(x):
    return (x[0]-9)**2 - x[0]*x[1] + 3*x[1]**2

def grad_f(x):
    return np.array([2*x[0]-x[1]-18, -x[0]+6*x[1]])

x0 = np.array([-15.8, -15.8])
A0 = np.identity(2)
H = np.matrix([
    [2, -1],
    [-1, 6]
])

def optimal_step_formula(x):
    s = -grad_f(x)
    sT = s[np.newaxis]
    gradT = grad_f(x)[np.newaxis]
    return(float(-(gradT.dot(s) / sT.dot(H).dot(s))))

In [4]:
S0 = -A0.dot(grad_f(x0))
l0 = optimal_step_formula(x0)
x1 = x0 - l0*grad_f(x0)
delta_x_0 = x1 - x0
delta_f_0 = grad_f(x1) - grad_f(x0)

In [5]:
A1 = A0 \
    + delta_x_0[np.newaxis].T.dot(delta_x_0[np.newaxis])/(delta_x_0[np.newaxis]).dot(delta_f_0) \
    - A0.dot(delta_f_0[np.newaxis].T).dot(delta_f_0[np.newaxis]).dot(A0)/(delta_f_0[np.newaxis]).dot(A0).dot(delta_f_0)
A1

array([[1.03254944, 0.10352354],
       [0.10352354, 0.18214486]])

In [6]:
S1 = - A1.dot(grad_f(x1))
l1 = optimal_step_formula(x1)
x2 = x1 - l1 * A1.dot(grad_f(x1))
delta_x_1 = x2 - x1
delta_f_1 = grad_f(x2) - grad_f(x1)

In [7]:
A2 = A1 \
    + delta_x_1[np.newaxis].T.dot(delta_x_1[np.newaxis])/(delta_x_1[np.newaxis]).dot(delta_f_1) \
    - A1.dot(delta_f_1[np.newaxis].T).dot(delta_f_1[np.newaxis]).dot(A1)/(delta_f_1[np.newaxis]).dot(A1).dot(delta_f_1)
A2

array([[0.54545455, 0.09090909],
       [0.09090909, 0.18181818]])

In [8]:
inv(H)

matrix([[0.54545455, 0.09090909],
        [0.09090909, 0.18181818]])

In [9]:
grad_f(x0).dot(grad_f(x1))

2.0463630789890885e-12

In [11]:
print('x0:', x0)
print('f(x0):', f(x0))
print('grad_f(x0):', grad_f(x0))
print('A0:', A0)

print('\nStep 1:')
print('S0:', S0)
print('l0:', l0)
print('x1:', x1)
print('f(x1):', f(x1))
print('grad_f(x1):', grad_f(x1))
print('delta_x_0:', delta_x_0)
print('delta_f_0:', delta_f_0)
print('A1:', A1)

print('\nStep 2:')
print('S1:', S1)
print('l1:', l1)
print('x2:', x2)
print('f(x2):', f(x2))
print('grad_f(x2):', grad_f(x2))
print('delta_x_1:', delta_x_1)
print('delta_f_1:', delta_f_1)
print('A2:', A2)

x0: [-15.8 -15.8]
f(x0): 1114.3200000000002
grad_f(x0): [-33.8 -79. ]
A0: [[1. 0.]
 [0. 1.]]

Step 1:
S0: [33.8 79. ]
l0: 0.21469429911998894
x1: [-8.54333269  1.16084963]
f(x1): 321.7287620527542
grad_f(x1): [-36.24751501  15.50843047]
delta_x_0: [ 7.25666731 16.96084963]
delta_f_0: [-2.44751501 94.50843047]
A1: [[1.03254944 0.10352354]
 [0.10352354 0.18214486]]

Step 2:
S1: [35.82186354  0.92769024]
l1: 0.2992028217322663
x2: [2.17466996 1.43841717]
f(x2): 49.66417937371964
grad_f(x2): [-15.08907724   6.45583305]
delta_x_1: [10.71800265  0.27756754]
delta_f_1: [21.15843777 -9.05259742]
A2: [[0.54545455 0.09090909]
 [0.09090909 0.18181818]]
